package featurecreep.api.bg;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import org.jboss.dmr.ModelNode;
import org.jboss.logging.Logger.Level;
import org.jboss.modules.Module;

import co.phoenixlab.dds.Dds;
import co.phoenixlab.dds.DdsImageDecoder;
import featurecreep.FeatureCreep;
import featurecreep.loader.FCLoaderBasicR5;


public class PackLoader {

	
	public static int pack_version = 4;
	public static String pack_name = "fcpack_" + pack_version;
	public static String fc_pack_location = new String (FeatureCreep.gamepath + "/resourcepacks/" + pack_name);
	
	public static void loadPacks(List<Module> modules)
	{

		
		for (int j = 0; j < FCLoaderBasicR5.modules.size(); j++) {

			try {
				exportResourcesFromModule(FCLoaderBasicR5.modules.get(j));
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	
		}	
		transferConvertedFiles();
		
		
		
	  	
		ModelNode node = new ModelNode();
		node.get("pack").get("description").set("featurecreep autogenerated texture or resource pack for loading some assets");
		node.get("pack").get("pack_format").set(pack_version);
		
		System.out.print(node.toJSONString(false));
	 

	      try {
	  		File myObj = new File(fc_pack_location + "/pack.mcmeta");
		  	System.out.println(myObj.toString());
		  	myObj.getParentFile().mkdirs();    		
	    		
		  	//I need to change this to make it only write if it is a new file
	    		FileWriter myWriter = new FileWriter(myObj);
	          myWriter.write(node.toJSONString(true));
			myWriter.close();
  		
	    		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	      
	      
	      
	      
	      //Not Currently Working, need to fix later
	     //File pack_file = new File(fc_pack_location);
	      //DirectoryResourcePack pack = new DirectoryResourcePack(pack_file);
	      //ResourcePackProfile pack_profile = new ResourcePackProfile("fcpack", true, () -> pack, Text.translatable("resourcePack.fc.name"), Text.translatable("resourcePack.fc.desc"), ResourcePackCompatibility.from(8, ResourceType.CLIENT_RESOURCES), ResourcePackProfile.InsertionPosition.TOP, true, ResourcePackSource.PACK_SOURCE_BUILTIN);

//	      pack_profile=fc_pack;
			
     
	      /*
	  	//private final ResourcePackProfile.Factory factory;

	      
	      
	      ModResourcePackCreator.register(DirectoryResourcePack("fcpack/"));
	      
	      ResourcePackProfile resourcePackProfile = ResourcePackProfile.of("Featurecreep Mods",
					true, () -> DirectoryResourcePack("fcpack/"), factory, ResourcePackProfile.InsertionPosition.TOP,
					ResourcePackSource.PACK_SOURCE_BUILTIN);

	*/		
      
	      
	      
	      
	      
			
			
			
			
	      
	      
	      
	}
	
	
		
	public static void exportResourcesFromModule (Module module) throws IOException
	{
		
	  //  for (int l = 0; l < module.getClassLoader().getDefinedPackages().length; l++) {

		
		
	//	System.out.println("Mod Paths "+module.getClassLoader().getDefinedPackages()[l].getName());
		System.out.print(module.getName());
		File tmpdir = new File(FeatureCreep.gamepath.toString()+"/tmp/");
		//if (module.getClassLoader().getDefinedPackages()[l].getName().equals("gfx"))
		//{
			//module.getClassLoader().getResourceAsStream("gfx");
			//System.out.println(module.getName() + " containts gfx");
		//	extractZipResource(PackLoader.class, module.getName() , tmpdir);
	    //}
		
		java.util.jar.JarFile jar = new java.util.jar.JarFile(module.getName());
		java.util.Enumeration enumEntries = jar.entries();
		
		while (enumEntries.hasMoreElements()) {
		    java.util.jar.JarEntry file = (java.util.jar.JarEntry) enumEntries.nextElement();
		    java.io.File f = new java.io.File(FeatureCreep.gamepath + "/tmp" + java.io.File.separator + file.getName());
		    
		    if (f.toString().contains("gfx")) {
		
		    	System.out.println(f);
		    	
		    f.getParentFile().mkdirs();
		    if (file.isDirectory()) { // if its a directory, create it
		        f.mkdir();
		        continue;
		    }
		    java.io.InputStream is = jar.getInputStream(file); // get the input stream
		    java.io.FileOutputStream fos = new java.io.FileOutputStream(f);
		    while (is.available() > 0) {  // write contents of 'is' to 'fos'
		    //if (f.toString().contains("gfx")) {
		    	fos.write(is.read());
		    //	System.out.println(file.toString());
		   //}
		    	
		    }
		    fos.close();
		    is.close();
		
		
		    }else if (f.toString().contains("orespawn") && f.toString().contains("config"))
		    {
		    	java.io.File osf = new java.io.File(FeatureCreep.gamepath  + java.io.File.separator + file.getName());
		    	System.out.println(osf);
		    	
		    	osf.getParentFile().mkdirs();
			    if (file.isDirectory()) { // if its a directory, create it
			    	osf.mkdir();
			        continue;
			    }
			    java.io.InputStream is = jar.getInputStream(file); // get the input stream
			    java.io.FileOutputStream fos = new java.io.FileOutputStream(osf);
			    while (is.available() > 0) {  // write contents of 'is' to 'fos'
			    //if (f.toString().contains("gfx")) {
			    	fos.write(is.read());
			    //	System.out.println(file.toString());
			   //}
			    	
			    }
			    fos.close();
			    is.close();
		    	
		    }
		
		
		    
		    
		    
		}
		jar.close();
		
		
	   // }
		
	}
	
	
	
	
	//https://stackoverflow.com/questions/5377104/how-to-extract-a-folder-from-jar
	
	   /**
	    * Extract the contents of a .zip resource file to a destination directory.
	    * <p>
	    * Overwrite existing files.
	    *
	    * @param myClass     The class used to find the zipResource.
	    * @param zipResource Must end with ".zip".
	    * @param destDir     The path of the destination directory, which must exist.
	    * @return The list of created files in the destination directory.
	    */
	   public static List<File> extractZipResource(Class myClass, String zipResource, File destFile)
	   { //!zipResource.toLowerCase().endsWith(".zip") ||
	      if (myClass == null || zipResource == null) //||  !Files.isDirectory(destDir))
	      {
	         throw new IllegalArgumentException("myClass=" + myClass + " zipResource=" + zipResource + " destDir=" + destFile);
	      }

	      ArrayList<File> res = new ArrayList<>();

	      try (InputStream is = myClass.getResourceAsStream(zipResource);
	              BufferedInputStream bis = new BufferedInputStream(is);
	              ZipInputStream zis = new ZipInputStream(bis))
	      {
	         ZipEntry entry;
	         byte[] buffer = new byte[2048];
	         while ((entry = zis.getNextEntry()) != null)
	         {
	            // Build destination file
	           //File destFile = destDir.resolve(entry.getName()).toFile();

	            if (entry.isDirectory())
	            {
	               // Directory, recreate if not present
	               if (!destFile.exists() && !destFile.mkdirs())
	               {
	            	     FeatureCreep.LOGGER.warn("extractZipResource() can't create destination folder : " + destFile.getAbsolutePath());
	               }
	               continue;
	            }
	            // Plain file, copy it
	            try (FileOutputStream fos = new FileOutputStream(destFile);
	                    BufferedOutputStream bos = new BufferedOutputStream(fos, buffer.length))
	            {
	               int len;
	               while ((len = zis.read(buffer)) > 0)
	               {
	                  bos.write(buffer, 0, len);
	               }
	            }
	            res.add(destFile);
	         }
	      } catch (IOException ex)
	      {
	         FeatureCreep.LOGGER.log(Level.FATAL, "extractZipResource() problem extracting resource for myClass=" + myClass + " zipResource=" + zipResource, ex);
	      }
	      return res;
	   }

	
	   
	   public static void transferConvertedFiles()
	   {
		   technologiesGFXtoItemPack();
		   terrainGFXtoBlockPack();
		   armourGFXtoItemPack();
	   }
	   
	   public static void technologiesGFXtoItemPack()
	   {
		   File file = new File(FeatureCreep.gamepath +"/tmp/gfx/interface/technologies/");
		   System.out.println(file);
		   String contents[] = file.list();
		    System.out.println("List of files and directories in the specified directory:");
		    //I need to make this multicore

		    
		    if (contents != null) {
		        for (int i = 0; i < contents.length; i++) {
		            File fil = new File(contents[i]);

	String[] filarr = fil.toString().split("!");
		            
	String modid = filarr[0];
	String item_name = filarr[1];
		            
		        File output = new File (fc_pack_location+"/assets/" + modid + "/textures/items/" + item_name.replace(".dds", "") + ".png");    
		            
		        if (!output.exists()) {
		        	output.getParentFile().mkdirs();
		        gfxtopng(new File(file.toString()+ "/" + fil.toString()), output);
		        }
		        
		            
		        }
		        
		        
		        }
		   
		   
	   }
	
	
	   
	   
	   
	   
	   public static void terrainGFXtoBlockPack()
	   {
		   File file = new File(FeatureCreep.gamepath +"/tmp/gfx/interface/terrains/");
		   System.out.println(file);
		   String contents[] = file.list();
		    System.out.println("List of files and directories in the specified directory:");
		    //I need to make this multicore

		    
		    if (contents != null) {
		        for (int i = 0; i < contents.length; i++) {
		            File fil = new File(contents[i]);

	String[] filarr = fil.toString().split("!");
		            
	String modid = filarr[0];
	String item_name = filarr[1];
		            
		        File output = new File (fc_pack_location+"/assets/" + modid + "/textures/blocks/" + item_name.replace(".dds", "") + ".png");    
		            
		        if (!output.exists()) {
		        	output.getParentFile().mkdirs();
		        gfxtopng(new File(file.toString()+ "/" + fil.toString()), output);
		        }
		        
		            
		        }
		        
		        
		        }
		   
		   
	   }
	   
	   
	   
	   
	   
	   public static void  armourGFXtoItemPack ()
	   {
	     File file = new File (FeatureCreep.gamepath + "/tmp/gfx/models/armour/");
	     System.out.println (file);
	     String contents[] = file.list ();
	     System.out.println (
	         "List of files and directories in the specified directory:");
	     // I need to make this multicore

	     if (contents != null)
	       {
	         for (int i = 0; i < contents.length; i++)
	           {
	             File fil = new File (contents[i]);

	             File output = new File (fc_pack_location + "/assets/minecraft/textures/models/armor/" + fil);

	             if (!output.exists())
	               {
	                 output.getParentFile().mkdirs();

	                 try
	                   {

	                     FileInputStream inputstream = new FileInputStream (file.toString () + "/" + fil.toString ());

	                     // Custom directory path on local machine
	                     FileOutputStream outputstream = new FileOutputStream (output.toString());

	                     int c;
	                     // Condition check
	                     // Reading the input file till there is input
	                     // present
	                     while ((c = inputstream.read ()) != -1)
	                       {

	                         // Writing to output file of the specified
	                         // directory
	                         outputstream.write (c);
	                       }
	                   }
	                 catch (IOException e)
	                   {
	                     // TODO Auto-generated catch block
	                     e.printStackTrace ();
	                   }

	                 // CopyTips
	                 // https://www.geeksforgeeks.org/different-ways-to-copy-files-in-java/

	                 //	gfxtopng(new File(file.toString()+ "/" +
	                 //fil.toString()), output);
	               }
	           }
	       }
	   }

	
	   
	   
	   
	   
	   
	   
	   
	   
	   
	   
	   
	   
	   
	   public static void gfxtopng(File path, File location)
	   {
			//   FeatureCreep.gamepath + fc_pack_location;
		   Dds dds = new Dds();
		   try {
			dds.read(Files.newByteChannel(path.toPath(), StandardOpenOption.READ));
			   DdsImageDecoder decoder = new DdsImageDecoder();
		        OutputStream outputStream = Files.newOutputStream(location.toPath().getParent().resolve(location.toPath().getFileName()), StandardOpenOption.CREATE,
		                StandardOpenOption.TRUNCATE_EXISTING);
		        decoder.convertToPNG(dds, outputStream);
		        outputStream.flush();
		        outputStream.close();	
		   
		   
		   } catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

			   
		   
	   }
	
	   
	   
	   
	   
	   
	   
}


