package featurecreep.api;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import org.jboss.dmr.ModelNode;

import net.minecraft.resource.DirectoryResourcePack;
import net.minecraft.resource.ResourcePackCompatibility;
import net.minecraft.resource.ResourcePackProfile;
import net.minecraft.resource.ResourcePackSource;
import net.minecraft.resource.ResourceType;
import net.minecraft.text.TranslatableText;

public class PackLoader {

	public static ResourcePackProfile fc_pack;
	
	public static void loadPacks()
	{

		
		
		
	  	
		ModelNode node = new ModelNode();
		node.get("pack").get("description").set("featurecreep autogenerated texture or resource pack for loading some assets");
		node.get("pack").get("pack_format").set(8);
		
		System.out.print(node.toJSONString(false));
	 

	      try {
	  		File myObj = new File("resourcepacks/fcpack_8/pack.mcmeta");
		  	System.out.println(myObj.toString());
		  	myObj.getParentFile().mkdirs();    		
	    		
		  	//I need to change this to make it only write if it is a new file
	    		FileWriter myWriter = new FileWriter(myObj);
	          myWriter.write(node.toJSONString(true));
			myWriter.close();
  		
	    		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	      
	      
	      
	      
	      //Not Currently Working, need to fix later
	      File pack_file = new File("resourcepacks/fcpack_8/");
	      DirectoryResourcePack pack = new DirectoryResourcePack(pack_file);
	      ResourcePackProfile pack_profile = new ResourcePackProfile("fcpack", true, () -> pack, new TranslatableText("resourcePack.fc.name"), new TranslatableText("resourcePack.fc.desc"), ResourcePackCompatibility.from(8), ResourcePackProfile.InsertionPosition.TOP, true, ResourcePackSource.PACK_SOURCE_BUILTIN);
	      
	      pack_profile=fc_pack;
			
     
	      /*
	  	//private final ResourcePackProfile.Factory factory;

	      
	      
	      ModResourcePackCreator.register(DirectoryResourcePack("fcpack/"));
	      
	      ResourcePackProfile resourcePackProfile = ResourcePackProfile.of("Featurecreep Mods",
					true, () -> DirectoryResourcePack("fcpack/"), factory, ResourcePackProfile.InsertionPosition.TOP,
					ResourcePackSource.PACK_SOURCE_BUILTIN);

	*/		
      
	      
	      
	      
	      
			
			
			
			
	      
	      
	      
	}
	
	
}
