package featurecreep.api.bg;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.function.Consumer;

import org.jboss.dmr.ModelNode;

import featurecreep.api.bg.datapacks.DataPackLoader;
import net.minecraft.resource.DirectoryResourcePack;
import net.minecraft.resource.ResourcePackProfile;
import net.minecraft.resource.ResourcePackProfile.Factory;
import net.minecraft.resource.ResourcePackProvider;
import net.minecraft.resource.ResourcePackSource;

public class FCPackLoad implements ResourcePackProvider{

	File loc;
	
	
	//From OpenLoader
public FCPackLoad(File location) {
        
    loc = location;    
        try {
            
            Files.createDirectories(location.toPath());
        }
        
        catch (final IOException e) {
            e.printStackTrace();
        }
        
    }
	


//	@Override
//	public <T extends ResourcePackProfile> void register(Map<String, T> var1, Factory<T> var2) {
//		// TODO Auto-generated method stub
//	}





	@Override
	public void register(Consumer<ResourcePackProfile> var1, Factory var2) {
		// TODO Auto-generated method stub
		
		
		

	  	
		ModelNode node = new ModelNode();
		node.get("pack").get("description").set("featurecreep autogenerated texture or resource pack for loading some assets");
		node.get("pack").get("pack_format").set(DataPackLoader.packnumber);
		
		System.out.print(node.toJSONString(false));
	 
	    
//	      ClientSpriteRegistryCallback.event(SpriteAtlasTexture.BLOCK_ATLAS_TEXTURE).register((resourceManager, sprites) -> {
//	          Objects.requireNonNull(sprites);
//	          SpriteLoader.addResources(resourceManager, "items", sprites::put);
//	          SpriteLoader.addResources(resourceManager, "blocks", sprites::put);

//	       }); //Special thanks to xtra arrows mod
	      
		
		
		
	      try {
	  		File myObj = new File(loc + "/pack.mcmeta");
		  	System.out.println(myObj.toString());
		  	myObj.getParentFile().mkdirs();    		
	    		
		  	//I need to change this to make it only write if it is a new file
			if (loc.toString().contains("datapack")) {
			  	FileWriter myWriter = new FileWriter(myObj);
		          myWriter.write(node.toJSONString(true));
				myWriter.close();
		}
  		
	    		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	
	
	      
	      ResourcePackProfile pack =     ResourcePackProfile.of("data"+PackLoader.pack_name, true, () -> new DirectoryResourcePack(loc), var2, ResourcePackProfile.InsertionPosition.TOP, ResourcePackSource.PACK_SOURCE_BUILTIN);
			
			 if (pack != null) {
	            
				 var1.accept(pack);
	        }
		
		
		
		
	}

}
