
modLoader="javafml" #mandatory


license="Public Domain"
loaderVersion="*"

[[mods]] #mandatory

# The modid of the mod
modId="featurecreep" #mandatory

version="5am0" #mandatory

displayName="FeatureCreep" #mandatory

authors="Asbestosstar" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''This file is temporary we will move back to modlauncher services later'''

