#Properties for LiteLoader 1.12.2
#Thu Aug 25 21:59:12 PDT 2022
forceInjection=false
soundManagerFix=true
tabAlwaysExpanded=false
version.featurecreepmc=42
brand=1.12.2-SNAPSHOT-r4CC2BB0-b4-4
search.jarfiles=true
search.mods=true
version.feaurecreepmc=41
log=stderr
updateCheckInterval=0
loadingbar=true
search.classpath=true
modInfoScreen=true
search.jar=false
disableJInput=false
checkForNewSnapshots=true
