package featurecreep.api.bg.datapacks;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import org.jboss.dmr.ModelNode;

import featurecreep.FeatureCreep;

public class DataPackLoader {

	public static String datapacklocation = new String(FeatureCreep.gamepath+"/resourcepacks/fcdatapack3/");//We can hardcode a datapack name as there are no datapacks past 1.12 afaik
	public static int packnumber = 3;
	
	public static void onInitialise(){
		File location = new File(datapacklocation);
		location.delete();
		location.deleteOnExit();
		
		
		ModelNode node = new ModelNode();
		node.get("pack").get("description").set("featurecreep autogenerated texture or resource pack for loading some assets");
		node.get("pack").get("pack_format").set(DataPackLoader.packnumber);
		
		System.out.print(node.toJSONString(false));
		
	      try {
		  		File myObj = new File(datapacklocation + "/pack.mcmeta");
			  	System.out.println(myObj.toString());
			  	myObj.getParentFile().mkdirs();    		
		    		
			  	//I need to change this to make it only write if it is a new file
				  	FileWriter myWriter = new FileWriter(myObj);
			          myWriter.write(node.toJSONString(true));
					myWriter.close();
			
	  		
		    		} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		
		//MinecraftClient.getInstance().getResourcePackManager().addPackFinder(new featurecreep.api.FCPackLoad(new java.io.File(featurecreep.api.datapacks.DataPackLoader.datapacklocation)));
	//	Set<ResourcePackProvider> provs =	(Set<ResourcePackProvider>)Mirror.of(MinecraftClient.getInstance().getResourcePackManager()).field("field_14227");
	//	provs.add(new FCPackLoad(new File(datapacklocation)));
		//.register was removed in a version of MC so we must mirror it
	//	OreFeatureGenerator.createOreFeatures();
		CraftZoneLoader.saveCraftNodes();
	//	CraftZoneLoader.saveMeltNodes();

	//	MinecraftClient.getInstance().getResourcePackManager().registerProvider(new FCPackLoad(new File(PackLoader.fc_pack_location)));

	//	Mirror.of(MinecraftClient.getInstance().getResourcePackManager()).method("registerFCPack").invoke();
	}
	
	
	
	//https://stackoverflow.com/questions/7768071/how-to-delete-directory-content-in-java
//	public static void deleteFolder(File folder) {
//	    File[] files = folder.listFiles();
//	    if(files!=null) { //some JVMs return null for empty dirs
//	        for(File f: files) {
//	            if(f.isDirectory()) {
//	                deleteFolder(f);
//	            } else {
//	                f.delete();
//	            }
//	        }
//	    }
//	    folder.delete();
//	}
	
	
	
}
