package featurecreep.api.bg;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileAttribute;
import java.util.function.Consumer;

import org.jboss.dmr.ModelNode;

import featurecreep.api.bg.datapacks.DataPackLoader;
import game.DirectoryResourcePack;
import game.IResourcePack;
import game.PackSources;
import game.ResourcePackInfo;
import game.ResourcePackProvider;
import game.ResourceType;

public class FCPackLoad implements ResourcePackProvider {
    File loc;

    public FCPackLoad(File location) {
        this.loc = location;
        try {
            Files.createDirectories((Path)location.toPath(), (FileAttribute[])new FileAttribute[0]);
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }



	
	
	class DirPackLoader implements ResourcePackInfo.Loader{
		@Override
		public IResourcePack open(String string) {
			// TODO Auto-generated method stub
			return new DirectoryResourcePack(string, loc.toPath(), false);
		}


		 
	 }


	@Override
	public void register(Consumer<ResourcePackInfo> consumer) {
		// TODO Auto-generated method stub
		 ModelNode node = new ModelNode();
	        node.get("pack").get("description").set("featurecreep autogenerated texture or resource pack for loading some assets");
	        node.get("pack").get("pack_format").set(DataPackLoader.packnumber);
	        System.out.print(node.toJSONString(false));
	        try {
	            File myObj = new File(this.loc + "/pack.mcmeta");
	            System.out.println(myObj.toString());
	            myObj.getParentFile().mkdirs();
	            if (this.loc.toString().contains((CharSequence)"datapack")) {
	                FileWriter myWriter = new FileWriter(myObj);
	                myWriter.write(node.toJSONString(true));
	                myWriter.close();
	            }
	        }
	        catch (IOException e) {
	            e.printStackTrace();
	        }
	        ResourcePackInfo.Loader packFactory = new DirPackLoader();
	       // ResourcePackInfo.Loader packFactory = name -> new DirectoryResourcePack(name, loc.toPath(), false);

	        ResourcePackInfo.PackMcMeta metadata = ResourcePackInfo.getPackMcMeta("datapack", packFactory);
	       // instantTextBoxType mutable_builder = instantTextBoxType.empty();//instantTextBoxType.translate("fcpack");
	        ResourcePackInfo pack = ResourcePackInfo.createResourcePack("datapack", null, true, packFactory, metadata,ResourceType.CLIENT_RESOURCES, ResourcePackInfo.InsertionPosition.TOP, true, PackSources.BUILTIN);
	        if (pack != null) {
	            System.out.println("Adding FCDatapack");
	            consumer.accept(pack);
	        }
		
	}
	
	
}
