package asbestosstar.bootstrap.minecraft;

import asbestosstar.bootstrap.BootstrapCommon;
import asbestosstar.bootstrap.sm.util.MixinRuntimeCoordinator;
import featurecreep.loader.FCLoaderBasicR9;
import featurecreep.loader.GameProvider;

/** Shared Minecraft bootstrap across vanilla and supported superloaders. */
public final class MinecraftCommonStartup {
    private static volatile boolean bootstrapped;
    private static volatile boolean started;
    public static final MinecraftHostKind HOST = MinecraftHostDetector.detect();
    public static final GameProvider prov = getGameProvider(HOST);

    private MinecraftCommonStartup() {}

    /** Loads FeatureCreep modules and configures only the transformation facilities actually required. */
    public static synchronized void bootstrap() {
        if (bootstrapped) return;

        BootstrapCommon.loader = new FCLoaderBasicR9(prov, 8);
        System.out.println("Starting FeatureCreep on " + HOST + ". Loading JBoss Modules:");
        BootstrapCommon.loader.loadMods();

        boolean moduleDeclaredInstrumentation = BootstrapCommon.loader.isHotswapNeeded();
        boolean mixinDeclaredInstrumentation = MixinRuntimeCoordinator.mixinsRequireInstrumentation(HOST);
        boolean needsInstrumentation = moduleDeclaredInstrumentation || mixinDeclaredInstrumentation;

        if (needsInstrumentation) {
            boolean managedLaunch = Boolean.getBoolean("featurecreep.launch.managed");
            boolean initAgent;
            if (BootstrapCommon.instrument != null && BootstrapCommon.agent_activated) {
                // Preferred path for launcher/server installs generated by FeatureCreep:
                // -javaagent installs Instrumentation before Minecraft starts.
                initAgent = true;
                System.out.println("FeatureCreep startup agent already active; dynamic attach is not needed.");
            } else if (managedLaunch) {
                // We own this launch configuration and therefore should never silently
                // fall back to self-attach. A missing premain agent means the generated
                // JSON/script is malformed or has been edited.
                initAgent = false;
                System.err.println("[FeatureCreep] Managed launch requested Instrumentation but the startup -javaagent did not initialize. Dynamic attach is disabled for managed launches.");
            } else {
                // Compatibility fallback for foreign launchers/embedders where FeatureCreep
                // cannot add JVM arguments itself. This is intentionally the last resort.
                initAgent = BootstrapCommon.initDefault();
                System.out.println("FeatureCreep dynamic agent fallback initialized because an unmanaged launch declared a transform need: " + initAgent);
            }

            if (initAgent) {
                prov.setInstrumentation(BootstrapCommon.instrument);
                if (moduleDeclaredInstrumentation) {
                    BootstrapCommon.loader.setupInstrumentation();
                }
            }
        } else {
            System.out.println("FeatureCreep Instrumentation not requested; agent attach is intentionally skipped.");
        }

        BootstrapCommon.loader.PremainAgents();
        MixinRuntimeCoordinator.initialize(HOST);
        bootstrapped = true;
    }

    public static void main(String[] args) {
        bootstrap();
        start();
    }

    public static synchronized void start() {
        bootstrap();
        if (started) return;
        BootstrapCommon.loader.runMods();
        started = true;
    }

    private static GameProvider getGameProvider(MinecraftHostKind host) {
        return switch (host) {
            case SPONGE -> new SpongePoweredGameProvider();
            case NEOFORGE -> new MedusaGameProvider();
            case FORGE -> new MCForgeGameProvider();
            case FABRIC -> new FabricGameProvider();
            case RIFT -> new RiftGameProvider();
            case NIL -> new NilGameProvider();
            case VANILLA -> new MinecraftGameProvider();
        };
    }
}
